name = "cdt/onchain"
version = "0.1.0"
compiler = "v1.1.23"
plutus = "v3"
license = "Apache-2.0"
description = "Certificate of Deposit Token (CDT) on-chain validators"

[repository]
user = "jonesnoaht"
project = "cdt"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.2.0"
source = "github"

[[dependencies]]
name = "aiken-lang/fuzz"
version = "v2.2.0"
source = "github"

[config]
